import json
import re
from datetime import datetime
from typing import Any

import streamlit as st


st.set_page_config(
    page_title="SCOPE Accelerator",
    page_icon="⚙️",
    layout="wide",
)


DEFAULT_SCHEMA = [
    {"name": "CustomerId", "type": "string"},
    {"name": "ProductId", "type": "string"},
    {"name": "UsageDate", "type": "DateTime"},
    {"name": "UsageCount", "type": "int"},
    {"name": "ModifiedDate", "type": "DateTime"},
]


def sanitize_filename(value: str) -> str:
    cleaned_value = re.sub(
        r"[^A-Za-z0-9_-]+",
        "_",
        value.strip(),
    )

    return cleaned_value.strip("_") or "generated_scope_job"


def validate_configuration(
    config: dict[str, Any],
) -> dict[str, Any]:
    errors: list[str] = []
    warnings: list[str] = []
    checks: list[str] = []

    job_name = config.get("job_name", "").strip()
    input_path = config.get("input_path", "").strip()
    output_path = config.get("output_path", "").strip()
    columns = config.get("columns", [])

    if job_name:
        checks.append("Job name is provided.")
    else:
        errors.append("Job name is required.")

    if input_path:
        checks.append("Input path is provided.")
    else:
        errors.append("Input path is required.")

    if output_path:
        checks.append("Output path is provided.")
    else:
        errors.append("Output path is required.")

    if input_path and output_path:
        if input_path.rstrip("/") == output_path.rstrip("/"):
            errors.append(
                "Input and output paths cannot be identical."
            )
        else:
            checks.append(
                "Input and output paths are different."
            )

    if columns:
        checks.append(
            f"{len(columns)} schema columns are configured."
        )
    else:
        errors.append(
            "At least one schema column is required."
        )

    if not config.get("filter_condition", "").strip():
        warnings.append(
            "No filter condition is configured."
        )

    return {
        "is_valid": len(errors) == 0,
        "errors": errors,
        "warnings": warnings,
        "checks": checks,
    }


def generate_scope_script(
    config: dict[str, Any],
) -> str:
    generated_at = datetime.now().strftime(
        "%Y-%m-%d %H:%M:%S"
    )

    extract_columns = []

    for index, column in enumerate(config["columns"]):
        comma = (
            ","
            if index < len(config["columns"]) - 1
            else ""
        )

        extract_columns.append(
            f"        {column['name']} "
            f"{column['type']}{comma}"
        )

    select_columns = []

    for index, column in enumerate(config["columns"]):
        comma = (
            ","
            if index < len(config["columns"]) - 1
            else ""
        )

        select_columns.append(
            f"        {column['name']}{comma}"
        )

    filter_condition = config[
        "filter_condition"
    ].strip()

    script = [
        "// =====================================================",
        "// Generated by SCOPE Accelerator",
        f"// Job: {config['job_name']}",
        f"// Environment: {config['environment']}",
        f"// Generated: {generated_at}",
        "// =====================================================",
        "",
        (
            f'#DECLARE InputPath string = '
            f'"{config["input_path"]}";'
        ),
        (
            f'#DECLARE OutputPath string = '
            f'"{config["output_path"]}";'
        ),
        "",
        "source_data =",
        "    EXTRACT",
        "\n".join(extract_columns),
        "    FROM @InputPath",
        "    USING DefaultTextExtractor();",
        "",
        "filtered_data =",
        "    SELECT",
        "\n".join(select_columns),
        "    FROM source_data",
    ]

    if filter_condition:
        script.append(
            f"    WHERE {filter_condition};"
        )
    else:
        script[-1] = script[-1] + ";"

    script.extend(
        [
            "",
            "OUTPUT filtered_data",
            "TO @OutputPath",
            "USING DefaultTextOutputter();",
        ]
    )

    return "\n".join(script)


st.title("⚙️ SCOPE Script Accelerator")

st.caption(
    "Generate a standardized SCOPE script from job metadata."
)

left_column, right_column = st.columns(
    [1, 1],
    gap="large",
)

with left_column:
    st.subheader("Job Configuration")

    with st.form("scope_form"):
        job_name = st.text_input(
            "Job name",
            value="CustomerUsageDaily",
        )

        environment = st.selectbox(
            "Environment",
            options=["DEV", "TEST", "PROD"],
        )

        input_path = st.text_input(
            "Input path",
            value="/data/raw/customer_usage/",
        )

        output_path = st.text_input(
            "Output path",
            value="/data/processed/customer_usage/",
        )

        schema_text = st.text_area(
            "Schema JSON",
            value=json.dumps(
                DEFAULT_SCHEMA,
                indent=2,
            ),
            height=250,
        )

        filter_condition = st.text_input(
            "Filter condition",
            value="UsageCount > 0",
        )

        submitted = st.form_submit_button(
            "Validate and Generate",
            type="primary",
            use_container_width=True,
        )

with right_column:
    st.subheader("Validation and Output")

    if submitted:
        try:
            columns = json.loads(schema_text)

            if not isinstance(columns, list):
                st.error(
                    "Schema JSON must contain a list."
                )
                st.stop()

        except json.JSONDecodeError as error:
            st.error(
                f"Invalid schema JSON: {error}"
            )
            st.stop()

        configuration = {
            "job_name": job_name,
            "environment": environment,
            "input_path": input_path,
            "output_path": output_path,
            "columns": columns,
            "filter_condition": filter_condition,
        }

        validation = validate_configuration(
            configuration
        )

        if validation["is_valid"]:
            st.success("Configuration is valid.")
        else:
            st.error(
                "Configuration contains errors."
            )

        for check in validation["checks"]:
            st.write(f"✅ {check}")

        for warning in validation["warnings"]:
            st.write(f"⚠️ {warning}")

        for error in validation["errors"]:
            st.write(f"❌ {error}")

        if validation["is_valid"]:
            generated_script = generate_scope_script(
                configuration
            )

            st.subheader("Generated SCOPE Script")

            st.code(
                generated_script,
                language="sql",
                line_numbers=True,
            )

            safe_job_name = sanitize_filename(
                job_name
            )

            st.download_button(
                label="Download .scope file",
                data=generated_script,
                file_name=f"{safe_job_name}.scope",
                mime="text/plain",
                use_container_width=True,
            )

            st.download_button(
                label="Download configuration",
                data=json.dumps(
                    configuration,
                    indent=2,
                ),
                file_name=f"{safe_job_name}.json",
                mime="application/json",
                use_container_width=True,
            )
    else:
        st.info(
            "Enter the job details and select "
            "'Validate and Generate'."
        )
